### ISSUE TITLE
Don't work setContent{} when call reCreate() in android 13 (API 30)

### ISSUE THREAD

**Issue by hossein-no1** [Dinesh2510/Jetpack-Compose-UI-Components-Material-3#1]
I try to change theme in my app
i call reCreate function and then i see white screen because don't call setContent{}
This problem was occurred only for android 13(API 30)

**Comment by Dinesh2510** [comment]
You mean to say you're attempting to change the theme with Jetpack compose?

**Comment by Dinesh2510** [comment]
Hi @hossein-no1 you can follow this code.
[Dark-and-Light-Theme-in-Jetpack-Compose](https://github.com/Dinesh2510/Dark-and-Light-Theme-in-Jetpack-Compose)
